- src/components/content/Icon/Icon.tsx
- src/components/content/Logo/Logo.tsx
- fix: remove icons from accessibility tree as they are purely decorative ([source](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden))
- fix: remove redundant info from logo alt text ([source](https://www.deque.com/blog/great-alt-text-introduction/#:~:text=At%20a%20minimum%2C%20the%20alt,%E2%80%9CUser%20Testing%20%E2%80%93%20Home%E2%80%9D))
> 1.1.1-non-text-content

- src/components/charts/LinearProgress/LinearProgress.tsx
- src/components/charts/StepProgress/StepProgress.tsx
making sure the child of linear progress always have space to calculate percentage from
> fix: add width to linear progress wrapper

- src/components/controls/inputs/TextInput/TextInput.tsx
- src/components/controls/selects/DefaultDropdownSelect/DefaultDropdownSelect.tsx
Decided together with Rui that all input components without labels should have rounded corders. This should make it possible for you to use `DefaultDropdownSelect` out of the box in Explore @jenseo!
> feat: make inputs without labels rounded

- src/components/views/Popover/Popover.stories.tsx
- src/components/views/Popover/Popover.tsx
This adds two things, the possibility to provide a title to the popover as a "full width" scaling for the responsive modes (no idea if this is an acceptable change from design or not)
> feat: add title to popover

- src/components/views/ElevatedSheets/ElevatedSheets.tsx
- src/components/views/PlainSheets/PlainSheets.tsx
Makes it possible to use things like isLoading and as.
> fix(sheets): extend button component props instead of generic button props

- src/components/controls/inputs/BaseInput/BaseInput.tsx
- src/components/controls/inputs/LabelTextInput/LabelTextInput.tsx
- src/components/controls/inputs/SearchInput/SearchInput.stories.tsx
- src/components/controls/inputs/SearchInput/SearchInput.tsx
- src/components/controls/inputs/TextInput/TextInput.stories.tsx
- src/components/controls/inputs/TextInput/TextInput.tsx
Preferring many components with simple props over few components with complex props has served us well. However, making `<TextInput>` and `<LabelTextInput>` separate, even though the label and the `border-radius` are the only differences, seems like it causes more overhead than it saves.
I'm preparing supporting `label` in the `<TextInput>` component here, so that we can deprecate or remove `<LabelTextInput>` in the next major.
> chore: rely on base input icon slots to simplify input components

- src/components/views/Popover/Popover.tsx
To enable using props like this:
https://github.com/einride/saga-admin/blob/146fe5955ded4060e7692c2227f3329ce2448897/src/components/OrganizationUsersList.tsx#L100
> fix: allow primary actions on popover buttons

- package.json
- src/components/typography/Caption/Caption.tsx
- src/components/typography/Link/Link.tsx
- src/components/typography/MegaTitle/MegaTitle.tsx
- src/components/typography/Paragraph/Paragraph.tsx
- src/components/typography/Title1/Title1.tsx
- src/components/typography/Title2/Title2.tsx
- src/components/typography/Title3/Title3.tsx
- yarn.lock
Right now, the `color` prop is leaking to the DOM, which is shouldn't do.
Using `shouldForwardProp` fixes that.
> chore: do not pass color prop to component

- src/components/content/UserAccessPoint/UserAccessPoint.tsx
> fix(UserAccessPoint): use elevated background color

- src/components/content/Tooltip/Tooltip.stories.tsx
- src/components/content/Tooltip/Tooltip.tsx
- src/components/layout/Box/Box.tsx
Makes multiline tooltips possible:
> feat(Tooltip): enable width prop

- src/components/views/Sheets/Sheets.stories.tsx
- src/components/views/Sheets/Sheets.tsx
To provide a proper non-modal sheets variant.
> fix(Sheets): deprecate withOverlay and closeOnClickOutside in favor of modal

- .github/workflows/chromatic.yml
With this, you can go to Checks -> Chromatic in a PR and you'll see a Chromatic deployment summary like this, where you can get a link to the Chromatic build for the PR:
> chore: add chromatic publish summary

- src/components/menus/Menu/Menu.tsx
Discovered that `isOpen` doesn't do anything, since Radix UI takes `open`. 
Can't do plain `open={isOpen}`, since `open` is typed as optional `boolean` and doesn't accept `undefined`.
> fix(Menu): map isOpen correctly to the Radix UI open prop

- package.json
- src/templates/TableView.stories.tsx
- yarn.lock
Skeleton from adding templates. Putting `Templates` in top level of Storybook hierarchy.
Adding a custom navbar for now, that can be improved on and reused if we need it in many templates.
There are a few open questions around the template design, as for example changing typography size on mobile, search button in navbar, highlighted table row, pagination, removed columns on mobile etc.
> chore: add table view template

- src/components/controls/inputs/BaseInput/BaseInput.tsx
- src/components/controls/inputs/TextInput/TextInput.stories.tsx
I disabled the focus state when the input field is set to read only.
> feat(BaseInput): add readonly style

- .github/workflows/chromatic.yml
- .storybook/main.js
- package.json
- yarn.lock
Before: Each build recreates all snapshots.
https://github.com/einride/ui/actions/runs/4182042035/jobs/7244649970#step:4:80
After: Each build recreates snapshots based on actual changes.
https://github.com/einride/ui/actions/runs/4182087742/jobs/7244750139#step:4:83
> feat: enable chromatic turbosnap

- .storybook/main.ts
- src/components/cards/Card/Card.stories.tsx
- src/components/charts/LinearGauge/LinearGauge.stories.tsx
- src/components/charts/LinearProgress/LinearProgress.stories.tsx
- src/components/charts/LinearVerticalProgress/LinearVerticalProgress.stories.tsx
- src/components/charts/StepGauge/StepGauge.stories.tsx
- src/components/charts/StepProgress/StepProgress.stories.tsx
- src/components/charts/StepVerticalProgress/StepVerticalProgress.stories.tsx
- src/components/content/Avatar/Avatar.stories.tsx
- src/components/content/Banner/Banner.stories.tsx
- src/components/content/Icon/Icon.stories.tsx
- src/components/content/Logo/Logo.stories.tsx
- src/components/content/Tooltip/Tooltip.stories.tsx
- src/components/content/UserAccessPoint/UserAccessPoint.stories.tsx
This will base story hierarchy in Storybook on file structure in `src/components` instead of explicitly giving the hierarchy with `title` for each story. The main benefit is that code discovery will be easier since it follows the same structure as Storybook out of the box.
Made the change only for a few components as a start. If you agree, we can make it for all/most. It's still possible to define `title` explicitly for cases where it's needed.
> chore: mirror file structure in storybook and code

- package.json
- yarn.lock
Same for mapbox-gl which is a dependency of react-map-gl
> feat: mapbox-gl as required dependency

- .changeset/friendly-pans-float.md
- packages/einride-ui/src/components/controls/selects/Select/Select.tsx
Fixes browser inconsistencies, where `<option>` is styled in a way that makes it impossible to see the options of Ubuntu Chrome:
> fix(Select): set colors

- .changeset/nervous-mice-report.md
- packages/einride-ui/src/components/controls/tabs/TabsTrigger.tsx
**Overview**
The inset shadow effect that is used to display a bottom border for `Tabs` is causing rendering issues on devices with very small screens and in situations where the browser is displaying the content in a "zoomed out" state. In those cases, the box shadow shines through on the sides of the tabs elements giving the impression of a border on the side of each tab.
Testing points to it being a rendering issue in the browser engine that can't be solved by adjusting the box shadow effect or adding some deeper trickery to circumvent the issue. This PR fixes the issue by removing the box shadow and replacing it with a bottom border.
**Note:** I still think that this is only a "developer problem". I can only reproduce this problem by using the Chrome Developer Tools "Device …
> fix: resolve zoom/small device issues in tabs component

- packages/einride-ui/src/components/controls/inputs/NumberInput/NumberInput.stories.tsx
- packages/einride-ui/src/components/controls/inputs/SearchInput/SearchInput.stories.tsx
- packages/einride-ui/src/components/controls/inputs/TextInput/TextInput.stories.tsx
- packages/einride-ui/src/components/controls/inputs/TimeInput/TimeInput.stories.tsx
- packages/einride-ui/src/components/controls/selects/SearchSelect/SearchSelect.stories.tsx
- packages/einride-ui/src/components/controls/textareas/Textarea/Textarea.stories.tsx
`toHaveErrorMessage` was deprecated a while back: https://github.com/testing-library/jest-dom/pull/503
> chore: replace deprecated testing function

- .changeset/seven-phones-poke.md
- packages/einride-ui/src/components/menus/Menu/Menu.tsx
Forward ref to `Menu` component.
Allow wrapping `Menu` component with a component who requires to pass ref to child component like `Tooltip`.
> fix: forward ref to Menu component

- .storybook/main.ts
> chore: use react-docgen-typescript for improved docs generation

- src/components/views/Sheets/Sheets.stories.tsx
- src/components/views/Sheets/Sheets.tsx
With the framer-motion 11.0.18 update the sheet opening animation stopped working. This commit fixes that by moving the motion animation to wrap the dialog content and overlay. The sheet exit animation has been broken prior to the 11.0.18 patch and this commit also fixes that by conditionally rendering the dialog root with isOpen, as is described in the framer motion docs.
Kudos to @Hadlabergman for debugging!
> fix: enusre sheet is animated correctly with new framer motion

- src/components/views/Alert/Alert.stories.tsx
- src/components/views/Alert/Alert.tsx
This commit is basically a copy of the changes in
d071be05e41ff407abe5ad7ccafdcaf4fa80f371, but made in Alert.tsx.
When framer-motion was updated it broke two kinds of components that we use: Sheets and Alerts. v8.0.1 only addressed the Sheet animation, but the issue still persisted in Alerts.
With these changes, the pop-ups in we use to switch between our two versions work again.
If you want me to provide more information or if you have directions on how to add tests to avoid this issue resurfacing, I would be more than happy to help out.
> fix: ensure alerts are animated correctly with new framer-motion
