einride/ui

.storybook/preview.js
src/components/typography/Caption/Caption.tsx
src/components/typography/MegaTitle/MegaTitle.tsx
src/components/typography/Paragraph/Paragraph.tsx
src/components/typography/Title1/Title1.tsx
src/components/typography/Title2/Title2.tsx
src/components/typography/Title3/Title3.tsx

Also set padding to 0 to avoid it being potentially set by other styling

Change padding to margin for typography

---

src/components/controls/selects/DropdownSelect/DropdownSelect.stories.tsx
src/components/controls/selects/DropdownSelect/DropdownSelect.tsx

fix: add option to have default value instead of placeholder for dropdown

---

.eslintrc.js
package.json
yarn.lock

chore: add eslint rule for having react in jsx scope

---

.storybook/main.js
package.json
yarn.lock

- chore(deps): add @storybook/addon-a11y
- chore: register @storybook/addon-a11y
- chore(deps): bump deps to latest

chore(deps): add @storybook/addon-a11y

---

src/components/controls/buttons/BaseButton/BaseButton.tsx
src/components/controls/buttons/IconButton/IconButton.tsx
src/components/controls/buttons/PrimaryButton/PrimaryButton.tsx
src/components/controls/buttons/SecondaryButton/SecondaryButton.tsx
src/components/controls/buttons/TertiaryButton/TertiaryButton.tsx
src/components/controls/buttons/WithIconButton/WithIconButton.tsx

To show focus indicator when focusing programmatically.

feat: use :focus-within instead of :focus on buttons

---

src/components/views/ElevatedSheets/ElevatedSheets.tsx
src/components/views/PlainSheets/PlainSheets.tsx

feat(sheets): make navigation sticky to top when scrolling

---

src/components/views/Sheets/Sheets.stories.tsx
src/components/views/Sheets/Sheets.tsx

This component will replace ElevatedSheets and PlainSheets, with prop that controls whether overlay should be used.

feat: add sheets component

---

src/components/content/Icon/Icon.stories.tsx
src/components/content/Icon/Icon.tsx

Add Unicode character "clockwise gapped circle arrow" to set of Einride icons: https://unicode-table.com/en/27F3/

feat(icons): add circleArrowRight

---

src/components/controls/inputs/BaseInput/BaseInput.tsx
src/components/controls/selects/Select/Select.tsx
src/components/controls/textareas/Textarea/Textarea.tsx

- feat(inputs): provide aria-invalid and aria-errormessage on invalid inputs
- feat(select): provide aria-invalid and aria-errormessage on invalid select
- feat(textarea): provide aria-invalid and aria-errormessage on invalid textarea

Provide aria-invalid and aria-errormessage on invalid inputs

---

src/components/content/UserAccessPoint/UserAccessPoint.tsx
src/lib/theme/dark.ts
src/lib/theme/light.ts
src/lib/theme/types.ts

- feat(theme): add primary inverted content color
- chore: deprecate reverse content color in favor of primary inverted

feat(theme): add primary inverted content color

---

package.json
src/components/controls/buttons/BaseButton/BaseButton.tsx

chore(BaseButton): make hasIcon prop optional

---

package.json
src/components/content/Avatar/Avatar.tsx
src/components/content/Avatar/getInitials.test.ts
src/components/content/Avatar/getInitials.ts
vite.config.js
yarn.lock

- chore(deps): add vitest
- chore: configure vitest
- chore: move getInitials function to separate file
- feat: make initial upper-case even if name is lower-case
- chore: add tess for getInitials

feat: make initials upper-case even if name is lower-case

---

src/components/controls/buttons/BaseButton/BaseButtonIcon.tsx
src/components/controls/buttons/PrimaryButton/PrimaryButton.tsx
src/components/controls/buttons/SecondaryButton/SecondaryButton.tsx
src/components/controls/buttons/TertiaryButton/TertiaryButton.tsx

- fix(buttons): remove min-width
- fix(buttons): align button icon properly

fix(buttons): align button icon properly

---

src/components/table/Table/Table.tsx
src/components/table/Tbody/Tbody.tsx
src/components/table/Td/Td.tsx
src/components/table/Th/Th.tsx
src/components/table/Thead/Thead.tsx

fix(table): make children optional

---

package.json
src/components/controls/radios/Radio/Radio.stories.tsx
yarn.lock

Force @testing-library/user-event to a version supporting radio focus behavior.

chore(Radio): add interaction tests

---

.github/workflows/chromatic.yml
src/components/controls/buttons/PrimaryButton/PrimaryButton.stories.tsx
src/components/controls/buttons/SecondaryButton/SecondaryButton.stories.tsx
src/components/controls/buttons/TertiaryButton/TertiaryButton.stories.tsx
src/components/controls/checkboxes/Checkbox/Checkbox.stories.tsx
src/components/controls/radios/Radio/Radio.stories.tsx
src/components/controls/tabs/Tabs.stories.tsx
src/components/feedback/Loader/Loader.stories.tsx
src/components/feedback/PageLoader/PageLoader.stories.tsx

- chore: disable visual regression testing
- chore: disabled snapshots for animating stories
- chore: use defaultChecked instead of checked when uncontrolled
- chore: fix story
- chore: run chromatic on push and pr to main

chromatic 2

---

src/components/controls/dates/DateRangePicker/DateRangePicker.stories.tsx

- chore(DateRangePicker): use 10th day instead of today
- chore(DateRangePicker): make keyboard tests consistent across all months

Fix: Date range picker tests

---

src/components/views/Alert/Alert.tsx
src/components/views/Sheets/Sheets.tsx

To prevent weird situations like this:

fix(Alert): put overlay above sheet

---

src/components/table/Th/Th.tsx
src/templates/TableView.stories.tsx

- feat(Th): make it possible to set text-align
- chore: add end-aligned number column to table template

feat(Th): make it possible to set text-align

---

src/components/controls/selects/SearchSelect/SearchSelect.stories.tsx
src/components/controls/selects/SearchSelect/SearchSelect.tsx
src/components/controls/selects/SearchSelect/types.ts
src/hooks/useScrollIntoView.ts

- document types
- limit dropdown size, enable scrolling
- use mantine scroll hook
- add tests
- a11y

Search select

---

src/components/controls/selects/SearchSelect/SearchSelect.tsx
src/components/controls/selects/SearchSelect/SearchSelectOption.tsx
src/components/menus/Menu/Content.tsx
src/components/menus/Menu/Item.tsx
src/components/menus/Menu/Menu.stories.tsx
src/components/menus/Menu/MenuContent.tsx
src/components/menus/Menu/MenuItem.tsx
src/components/menus/Menu/MenuTrigger.tsx
src/components/menus/Menu/Trigger.tsx
src/components/menus/Menu/index.ts
src/components/menus/MenuItem/MenuItem.stories.tsx
src/components/menus/MenuItem/MenuItem.tsx
src/components/views/Sheets/Sheets.stories.tsx

@filiptammergard just an idea how to structure the menu. What do you think?

feat(MenuItem): separate reusable MenuItem

---

src/components/controls/inputs/SearchInput/SearchInput.tsx
src/components/controls/selects/SearchSelect/SearchSelectInput.tsx

- style SearchInput clear button
- style SearchSelectInput clear button
- fix (un)controlled state of SearchInput
- focus SearchInput after clear

feat: style clear button focus state

---

.prettierignore
.storybook/preview.jsx
package.json
src/lib/storybook/SnapshotWrapper.tsx

I see two potential issues:
1. `if (options.name === "Snapshot")` seems error prone
2. If unique values are passed into the components they are not unique anymore
3. Some colors are set on `body` level

chore: render snapshots in light and dark mode

---

package.json
src/components/mapping/Charger.stories.tsx
src/components/mapping/ChargerSmall.stories.tsx
src/components/mapping/ConventionalTruck.stories.tsx
src/components/mapping/Pod.stories.tsx
src/components/mapping/Site.stories.tsx
src/components/mapping/SiteHovered.stories.tsx
src/components/mapping/SiteSelected.stories.tsx
src/components/mapping/SiteSmall.stories.tsx
src/components/mapping/SiteWithCharger.stories.tsx
src/components/mapping/SiteWithChargerSmall.stories.tsx
yarn.lock

Converting to the new CSF format. More information here: https://storybook.js.org/blog/component-story-format-3-0/

chore: convert mapping stories to CSF3

---

src/lib/theme/dark.ts
src/lib/theme/light.ts

Based on the recent updates in https://www.figma.com/file/zX0qOVghVidk8vWZdd2nwO/Primitives?node-id=1783%3A735&t=NnCPlbqWQxgWe16u-0.

feat(colors): update warning and accent colors

---

src/components/menus/Menu/Menu.stories.tsx
src/components/menus/Menu/MenuContent.tsx

Unfortunately radix doesn't provide a menu-overlay

feat(Menu): add overlay

---

.storybook/main.js
.storybook/preview.jsx

Reverts einride/ui#1133
Revert due to merge conflicts, when reverting https://github.com/einride/ui/pull/1132

Revert "chore: turn main.js and preview.jsx into typescript"

---

.storybook/main.ts
.storybook/preview.tsx

Revert "Revert "chore: turn main.js and preview.jsx into typescript""

---

STYLE.md

Here are some of the styles we're currently kind of following and that I think we should follow going forward. Thoughts?

chore: add project specific style guide

---

packages/einride-ui/package.json
packages/einride-ui/src/components/controls/dates/Calendar/Calendar.stories.tsx
packages/einride-ui/src/components/controls/dates/DatePicker/DatePicker.stories.tsx
packages/einride-ui/src/components/controls/dates/DateRangePicker/DateRangePicker.stories.tsx
packages/einride-ui/src/components/controls/dates/RangeCalendar/RangeCalendar.stories.tsx
yarn.lock

Includes https://github.com/mantinedev/mantine/pull/3728.

fix(dates): bump mantine dependencies for fixed keyboard navigation

---

packages/einride-ui/src/components/cards/Card/Card.mdx
packages/einride-ui/src/components/content/Icon/Icon.mdx
packages/einride-ui/src/components/content/Logo/Logo.mdx
packages/einride-ui/src/components/content/Tooltip/Tooltip.mdx
packages/einride-ui/src/components/controls/buttons/LinkButton/LinkButton.mdx
packages/einride-ui/src/components/controls/buttons/LinkButton/LinkButton.stories.tsx
packages/einride-ui/src/components/controls/buttons/PrimaryButton/PrimaryButton.mdx
packages/einride-ui/src/components/controls/buttons/SecondaryButton/SecondaryButton.mdx

- chore(IconButton): add docs
- chore(LinkButton): add docs

icon button

---

.changeset/thick-gifts-build.md
.changeset/weak-pandas-invite.md
packages/einride-ui/src/components/charts/LinearGauge/LinearGauge.mdx
packages/einride-ui/src/components/charts/LinearGauge/LinearGauge.stories.tsx
packages/einride-ui/src/components/charts/LinearGauge/LinearGauge.tsx
packages/einride-ui/src/components/charts/LinearGauge/LinearGaugeProgress.tsx
packages/einride-ui/src/components/layout/Box/Box.tsx
packages/einride-ui/src/lib/theme/props.ts

- fix(LinearGauge): correct required props
- feat(Box): allow flexShrink prop

linear gauge

---

.changeset/thin-icons-grab.md
packages/einride-ui/src/components/content/Tooltip/Tooltip.stories.tsx
packages/einride-ui/src/components/content/Tooltip/Tooltip.tsx

Added the option to style the tooltip content wrapper as well as change it's position.

fix: add styling and position props to tooltip

---

.changeset/warm-shirts-help.md
packages/einride-ui/src/index.ts

Needed to setup color modes storybook plugins

fix: export themes

---

.changeset/sour-trees-itch.md
packages/einride-ui-dates/package.json
packages/einride-ui-labs/package.json
packages/einride-ui-maps/package.json
packages/einride-ui/package.json

**Overview**
Remove the node version requirements from all packages.

fix: remove node version requirements

---

.changeset/grumpy-meals-study.md
packages/einride-ui/src/components/content/Icon/Icon.tsx

Needed by team growth. We've had a plus icon but not a minus icon for a long time.

feat: add minus icon

---

.changeset/smooth-guests-know.md
packages/einride-ui-dates/src/components/DatePicker/DatePicker.tsx
packages/einride-ui-dates/src/components/DatePickerInput/DatePickerInput.tsx
packages/einride-ui-dates/src/components/DateRangePicker/DateRangePicker.tsx
packages/einride-ui-dates/src/components/DateRangePickerInput/DateRangePickerInput.tsx
packages/einride-ui/src/components/controls/dates/Calendar/Calendar.tsx
packages/einride-ui/src/components/controls/dates/DatePicker/DatePicker.tsx
packages/einride-ui/src/components/controls/dates/DateRangePicker/DateRangePicker.tsx
packages/einride-ui/src/components/controls/dates/RangeCalendar/RangeCalendar.tsx

Since that causes problem when using date pickers inside sheets.

fix(DIVOPS-3): do not render date picker popovers in portals

---

.changeset/seven-phones-poke.md
packages/einride-ui/src/components/menus/Menu/Menu.tsx

Revert "fix: forward ref to Menu component"

---

yarn.lock

To resolve vulnerability in vite: https://github.com/einride/ui/security/dependabot/64

chore: regen lock file

---

.backstage/component-einride-ui.yaml
.github/workflows/chromatic.yml
.github/workflows/codeql-analysis.yml
.github/workflows/release.yml
.github/workflows/review.yml
.github/workflows/storybook-tests.yml
.releaserc.js
README.md
package.json

The default branch was recently changed from `main` to `master`, but not all setup was changed accordingly.

chore: change occurances of branch main to master
